### ISSUE TITLE
What 's the RTF  on CPU?

### ISSUE THREAD

**Issue by zhangsanfeng86** [keonlee9420/FastPitchFormant#1]
Hi,
Thank U for share!
What 's the RTF  on CPU?

**Comment by keonlee9420** [comment]
Hi @zhangsanfeng86 , the current implementation samples a single audio in about 0.0372 RTF (including vocoder) on CPU.

**Comment by zhangsanfeng86** [comment]
@keonlee9420 thank you for your reply! 
and how about the RTF without vocoder on CPU?

**Comment by keonlee9420** [comment]
Sorry but I currently don’t have time to take it. It would be better if you can share the information.

**Comment by keonlee9420** [comment]
Close due to inactivity.
